project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1"
            href: "Hand-on_ex/Hand-on_ex1/Hands-on_Ex01.qmd"
          - text: "Hands-on Exercise 2"
            href: "Hand-on_ex/Hand-on-ex2/Hand-on-ex2.qmd"
          - text: "Hands-on Exercise 3a"
            href: "Hand-on_ex/Hand-on-ex3/Hands-on_ex3a.qmd"
          - text: "Hands-on Exercise 3b"
            href: "Hand-on_ex/Hand-on-ex3/Hand-on_ex3b.qmd"
    right:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
