project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1"
            href: "Hand-on_ex/Hand-on_ex1/Hands-on_Ex01.qmd"
          - text: "Hands-on Exercise 2"
            href: "Hand-on_ex/Hand-on_ex2/Hand-on-ex2.qmd"
          - text: "Hands-on Exercise 3.1"
            href: "Hand-on_ex/Hand-on_ex3/Hands-on_ex3.1.qmd"
          - text: "Hands-on Exercise 3.2"
            href: "Hand-on_ex/Hand-on_ex3/Hand-on_ex3.2.qmd"
          - text: "Hands-on Exercise 4.1"
            href: "Hand-on_ex/Hand-on_ex4/Hands-on_Ex4.1.qmd"
          - text: "Hands-on Exercise 4.2"
            href: "Hand-on_ex/Hand-on_ex4/Hands-on_Ex4.2.qmd"
          - text: "Hands-on Exercise 4.3"
            href: "Hand-on_ex/Hand-on_ex4/Hands-on_Ex4.3.qmd"
          - text: "Hands-on Exercise 4.4"
            href: "Hand-on_ex/Hand-on_ex4/Hands-on_Ex4.4.qmd"
          - text: "Hands-on Exercise 5.1"
            href: "Hand-on_ex/Hand-on_ex5/Hands-on_Ex5.1.qmd" 
          - text: "Hands-on Exercise 5.2"
            href: "Hand-on_ex/Hand-on_ex5/Hands-on_Ex5.2.qmd"
          - text: "Hands-on Exercise 5.3"
            href: "Hand-on_ex/Hand-on_ex5/Hands-on_Ex5.3.qmd"
          - text: "Hands-on Exercise 5.4"
            href: "Hand-on_ex/Hand-on_ex5/Hands-on_Ex5.4.qmd"
          - text: "Hands-on Exercise 5.5"
            href: "Hand-on_ex/Hand-on_ex5/Hands-on_Ex5.5.qmd"
          - text: "Hands-on Exercise 7"
            href: "Hand-on_ex/Hand-on_ex7/Hands-on_Ex7.qmd"
      - text: "Take Home Exercise"
        menu:
          - text: "Take Home Exercise"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.qmd"
    right:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
